title: 50GlobalTech | Shop Smartphones,Tablets,Smart watches online
url: "https://drutech6.github.io"
baseurl: "/50GlobalTech"

defaults:
  - scope:
      path: "_layouts/default.html"
    values:
      layout: "default"
incremental: true

collections:
  categories:
    output: false
    permalink: /none/

